Task 1 : Import the numpy library and check its version.

In [8]:
import numpy as np
print(np.__version__)

2.2.6


Task 2: 
-> Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
->Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
->Generate an array of 10 evenly spaced values between 0 and 5.

In [ ]:
list = [1, 2, 3, 4, 5]
array = np.array(list)

print(f"1D Array:\n {array}")

1D Array:
 [1 2 3 4 5]
(5,)


In [ ]:
array_2D = np.arange(1,10).reshape(3,3)
print(f"2D Array:\n{array_2D}")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
evenly_space_arr = np.linspace(0, 5, 10)
print(f"Array generated by evenly spaced:\n {evenly_space_arr}")

Array generated by evenly spaced:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Task 3:
-> Access the element in the second row, third column of the 2D array you created above.
-> Slice the first two rows and the first two columns from the same array.
-> Modify the value in the last row and first column to 100.

In [32]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(f"Creating a array: \n{arr}")
element_access_inArray = arr[1, 2]
print(f"Element in second row and from third column: {element_access_inArray}")

Creating a array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element in second row and from third column: 6


In [35]:
slice_inArray = arr[:2, :2]
print(f"Sliced array in first two rows and two columns: {slice_inArray}")

Sliced array in first two rows and two columns: [[1 2]
 [4 5]]


In [36]:
arr[-2, 1] = 30
print(f"Modified array of second row and its second column: \n {arr}")

Modified array of second row and its second column: 
 [[ 1  2  3]
 [ 4 30  6]
 [ 7  8  9]]


Task 4:
-> Find the shape, size, and data type of the 2D array.
-> Change the 1D array into a 2D array of shape (5,1).
-> Flatten a multi-dimensional array back into a 1D array.

In [41]:
array_2D = np.array([[1,2,3],
                     [5,6,7]])
print(f"2D Array:\n{array_2D}")
print(f"Shape of array:\n{array_2D.shape}")
print(f"Data type of 2D array:\n{array_2D.dtype}")

2D Array:
[[1 2 3]
 [5 6 7]]
Shape of array:
(2, 3)
Data type of 2D array:
int64


Task 5:

-> Add 5 to every element in the 1D array.
-> Multiply the 2D array by 3.
-> Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [49]:
add_five_inArray = np.array([1,2,3,4,5])
add_five_inArray += 5
print(f"Add five in every element in 1D array:\n {add_five_inArray}")

Add five in every element in 1D array:
 [ 6  7  8  9 10]


In [57]:
mul_array = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

mul_array *= 3
print(f"2D Array multiple by 3:\n {mul_array}")

2D Array multiple by 3:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [59]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6], [7,8]])

matrix_mul = np.dot(A,B)
print(f"Matrix multiplication using dot product: \n{matrix_mul}")

Matrix multiplication using dot product: 
[[19 22]
 [43 50]]


Task 6:
-> Create a 3x3 matrix of ones and a 1D array of length 3.
-> Add the 1D array to each row of the matrix using broadcasting.

In [64]:
matrix = np.ones((3,3))
print(f"A 3*3 matrix of ones: \n {matrix}") 
#----- 1D Array of length of three ------
arr_1d = np.array([1,2,3])
print(f"1D array:\n {arr_1d}")
print(f"1D array:\n",len(arr_1d)) 

A 3*3 matrix of ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1D array:
 [1 2 3]
1D array:
 3


In [65]:
final = matrix + arr_1d
print(f"Adding 1D array in matrix using Broadcasting:\n{final}")

Adding 1D array in matrix using Broadcasting:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
